### Testen des Use Case: ReadAllCustomsfc
Get  http://localhost:4004/readallcustomsfc/readAllSfcData()

### Testen des Use Case: ReadCustomsfc für sfc= BW01 and plant= BW
GET http://localhost:4004/readcustomsfc/readSfcData(sfc='BW01',plant='BW')

### Testen des Use Case: CreateCustomsfc
POST http://localhost:4004/createcustomsfc/createSfcData
Content-Type: application/json

{
    "sfc": "BW01",
    "plant": "BW",
    "datafield": "Stage",
    "datafieldvalue": "Abrüsten"
}

### Testen des Use Case: CreateCustomsfc
POST http://localhost:4004/createcustomsfc/createSfcData
Content-Type: application/json

{
    "sfc": "BW01",
    "plant": "BW",
    "datafield": "Stage",
    "datafieldvalue": "Verpacken"
}

### Testing des Use Case: ChangeCustomsfc
### (Dafür muss der vorherige Request gesendet werden, da der Datensatz sonst nicht existiert.)
POST http://localhost:4004/changecustomsfc/changeSfcData
Content-Type: application/json

{
    "sfc": "BW01",
    "plant": "BW",
    "datafield": "Stage",
    "datafieldvalue": "Warten",
    "datafieldnew": "Stage",
    "datafieldvaluenew": "Einpacken"
}